const GET_DATA_REQUEST = 'customproduct/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'customproduct/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'customproduct/GET_DATA_REQUEST_FAILED'

const ADD_DATA_REQUEST = 'customproduct/ADD_DATA_REQUEST'
const ADD_DATA_REQUEST_SUCCESS = 'customproduct/ADD_DATA_REQUEST_SUCCESS'
const ADD_DATA_REQUEST_FAILED = 'customproduct/ADD_DATA_REQUEST_FAILED'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,
  ADD_DATA_REQUEST,
  ADD_DATA_REQUEST_SUCCESS,
  ADD_DATA_REQUEST_FAILED
}