const GET_ALL_ITEMS_REQUEST = 'similarto/GET_ALL_ITEMS_REQUEST'
const GET_ALL_ITEMS_REQUEST_SUCCESS = 'similarto/GET_ALL_ITEMS_REQUEST_SUCCESS'
const GET_ALL_ITEMS_REQUEST_FAILED = 'similarto/GET_ALL_ITEMS_REQUEST_FAILED'

export {
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_REQUEST_SUCCESS,
  GET_ALL_ITEMS_REQUEST_FAILED,
}
