const GET_ALL_ITEMS_REQUEST = 'similarto/GET_ALL_ITEMS_REQUEST'
const GET_ALL_ITEMS_REQUEST_SUCCESS = 'similarto/GET_ALL_ITEMS_REQUEST_SUCCESS'
const GET_ALL_ITEMS_REQUEST_FAILED = 'similarto/GET_ALL_ITEMS_REQUEST_FAILED'

const SET_ITEM_VALUE = 'similarto/SET_ITEM_VALUE'
const SET_ITEM_VALUE_SUCCESS = 'similarto/SET_ITEM_VALUE_SUCCESS'

export {
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_REQUEST_SUCCESS,
  GET_ALL_ITEMS_REQUEST_FAILED,

  SET_ITEM_VALUE,
  SET_ITEM_VALUE_SUCCESS
}
