const GET_DATA_REQUEST = 'similarto/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'similarto/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'similarto/GET_DATA_REQUEST_FAILED'

const SET_ITEM_VALUE = 'similarto/SET_ITEM_VALUE'
const SET_ITEM_VALUE_SUCCESS = 'similarto/SET_ITEM_VALUE_SUCCESS'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,

  SET_ITEM_VALUE,
  SET_ITEM_VALUE_SUCCESS
}
