const GET_ALL_ITEMS_REQUEST = 'cart/GET_ALL_ITEMS_REQUEST'
const GET_ALL_ITEMS_REQUEST_SUCCESS = 'cart/GET_ALL_ITEMS_REQUEST_SUCCESS'
const GET_ALL_ITEMS_REQUEST_FAILED = 'cart/GET_ALL_ITEMS_REQUEST_FAILED'

const ADD_TO_CART = 'cart/ADD_TO_CART'
const REMOVE_FROM_CART = 'cart/REMOVE_FROM_CART'
const REMOVE_ITEM_FROM_CART = 'cart/REMOVE_ITEM_FROM_CART'

export {
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_REQUEST_SUCCESS,
  GET_ALL_ITEMS_REQUEST_FAILED,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  REMOVE_ITEM_FROM_CART,
}
