const GET_ALL_ITEMS_REQUEST = 'branchoffices/GET_ALL_ITEMS_REQUEST'
const GET_ALL_ITEMS_REQUEST_SUCCESS =	'branchoffices/GET_ALL_ITEMS_REQUEST_SUCCESS'
const GET_ALL_ITEMS_REQUEST_FAILED =	'branchoffices/GET_ALL_ITEMS_REQUEST_FAILED'

export {
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_REQUEST_SUCCESS,
  GET_ALL_ITEMS_REQUEST_FAILED,
}
