const GET_DATA_REQUEST = 'branchoffices/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS =	'branchoffices/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED =	'branchoffices/GET_DATA_REQUEST_FAILED'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,
}
