const GET_DATA_REQUEST_REVIEWS = 'getoneitem/reviews/GET_DATA_REQUEST_REVIEWS'
const GET_DATA_REQUEST_SUCCESS_REVIEWS = 'getoneitem/reviews/GET_DATA_REQUEST_SUCCESS_REVIEWS'
const GET_DATA_REQUEST_FAILED_REVIEWS = 'getoneitem/reviews/GET_DATA_REQUEST_FAILED_REVIEWS'

export {
  GET_DATA_REQUEST_REVIEWS,
  GET_DATA_REQUEST_SUCCESS_REVIEWS,
  GET_DATA_REQUEST_FAILED_REVIEWS,
}
