const GET_DATA_REQUEST = 'favorites/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'favorites/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'favorites/GET_DATA_REQUEST_FAILED'

const TOOGLE_FAVORITE = 'favorites/TOOGLE_FAVORITE'
const TOOGLE_FAVORITE_SUCCESS = 'favorites/TOOGLE_FAVORITE_SUCCESS'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,

  TOOGLE_FAVORITE,
  TOOGLE_FAVORITE_SUCCESS,
}
