const GET_ALL_ITEMS_REQUEST = 'addresses/GET_ALL_ITEMS_REQUEST'
const GET_ALL_ITEMS_REQUEST_SUCCESS = 'addresses/GET_ALL_ITEMS_REQUEST_SUCCESS'
const GET_ALL_ITEMS_REQUEST_FAILED = 'addresses/GET_ALL_ITEMS_REQUEST_FAILED'

export {
    GET_ALL_ITEMS_REQUEST,
    GET_ALL_ITEMS_REQUEST_SUCCESS,
    GET_ALL_ITEMS_REQUEST_FAILED
}