# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
   # iOS Lanes
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: 'test', project_dir: './android')
  end

  desc "Build aab package"
  lane :aab do
    store_password = prompt(text: "Signing Store Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    releaseFilePath = File.join(Dir.pwd, "../android/app", "app_keyname.keystore")
    gradle(task: 'clean', project_dir: './android')
    gradle(
      task: "incrementVersionCode",
      project_dir: "./android"
    )

    git_commit(
      path: "android/gradle.properties",
      message: "Version Bump"
    )

    gradle(
      task: 'bundle',
      project_dir: './android',
      build_type: 'Release',
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "app_keyalias",
        "android.injected.signing.key.password" => key_password,
      }
    )

    appcenter_upload(
      api_token: "7e699472a63d76216b0fc92d37df33a9e3bbeea6",
      owner_name: "AppSoftLog",
      owner_type: "organization", # Default is user - set to organization for appcenter organizations
      app_name: "App-biolerplate",
      file: "./android/app/build/outputs/bundle/release/app-release.aab",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end
  
  desc 'Build the Android APKs.'
  lane :apk do
    store_password = prompt(text: "Signing Store Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    releaseFilePath = File.join(Dir.pwd, "../android/app", "app_keyname.keystore")
    gradle(task: 'clean', project_dir: './android')
    gradle(
      task: "incrementVersionCode",
      project_dir: "./android"
    )

    git_commit(
      path: "android/gradle.properties",
      message: "Version Bump"
    )

    gradle(
      task: 'assemble',
      project_dir: './android',
      build_type: 'Release',
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "app_keyalias",
        "android.injected.signing.key.password" => key_password,
      }
    )
  end
end
