const SIGNIN = 'user/SIGNIN'
const SIGNIN_SUCCESS = 'user/SIGNIN_SUCCESS'
const SIGNIN_FAILED = 'user/SIGNIN_FAILED'

const LOGOUT = 'user/LOGOUT'
const LOGOUT_SUCCESS = 'user/LOGOUT_SUCCESS'

const SIGNUP = 'user/SIGNUP'
const SIGNUP_SUCCESS = 'user/SIGNUP_SUCCESS'

const RECOVERY_PASS = 'user/RECOVERY_PASS'
const RECOVERY_PASS_SUCCESS = 'user/RECOVERY_PASS_SUCCESS'

export {
    SIGNIN,
    SIGNIN_SUCCESS,
    SIGNIN_FAILED,

    LOGOUT,
    LOGOUT_SUCCESS,
    
    SIGNUP,
    SIGNUP_SUCCESS,
    
    RECOVERY_PASS,
    RECOVERY_PASS_SUCCESS
}