const SIGNIN = 'user/SIGNIN'
const SIGNIN_SUCCESS = 'user/SIGNIN_SUCCESS'
const SIGNIN_FAILED = 'user/SIGNIN_FAILED'

const LOGOUT = 'user/LOGOUT'
const LOGOUT_SUCCESS = 'user/LOGOUT_SUCCESS'

const SIGNUP = 'user/SIGNUP'
const SIGNUP_SUCCESS = 'user/SIGNUP_SUCCESS'

const RECOVERY_PASS = 'user/RECOVERY_PASS'
const RECOVERY_PASS_SUCCESS = 'user/RECOVERY_PASS_SUCCESS'

const AUTHSOCIALMEDIA = 'user/AUTHSOCIALMEDIA'
const AUTHSOCIALMEDIA_SUCCESS = 'user/AUTHSOCIALMEDIA_SUCCESS'
const AUTHSOCIALMEDIA_FAILED = 'user/AUTHSOCIALMEDIA_FAILED'

const CHECK_TOKEN = 'user/CHECK_TOKEN'
const CHECK_TOKEN_SUCCESS = 'user/CHECK_TOKEN_SUCCESS'

const GET_USER_DATA = 'user/GET_USER_DATA'
const GET_USER_DATA_SUCCESS = 'user/GET_USER_DATA_SUCCESS'

export {
  SIGNIN,
  SIGNIN_SUCCESS,
  SIGNIN_FAILED,
  LOGOUT,
  LOGOUT_SUCCESS,
  SIGNUP,
  SIGNUP_SUCCESS,
  RECOVERY_PASS,
  RECOVERY_PASS_SUCCESS,
  AUTHSOCIALMEDIA,
  AUTHSOCIALMEDIA_SUCCESS,
  AUTHSOCIALMEDIA_FAILED,
  CHECK_TOKEN,
  CHECK_TOKEN_SUCCESS,
  GET_USER_DATA,
  GET_USER_DATA_SUCCESS
}
