const GET_DATA_REQUEST = 'favorites/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'favorites/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'favorites/GET_DATA_REQUEST_FAILED'

const TOGGLE_FAVORITE = 'favorites/TOGGLE_FAVORITE'
const TOGGLE_FAVORITE_SUCCESS = 'favorites/TOGGLE_FAVORITE_SUCCESS'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,

  TOGGLE_FAVORITE,
  TOGGLE_FAVORITE_SUCCESS,
}
