const GET_DATA_REQUEST = 'themepicker/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'themepicker/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'themepicker/GET_DATA_REQUEST_FAILED'

const SWITCH_THEME = 'themepicker/SWITCH_THEME'
const SWITCH_THEME_SUCCESS = 'themepicker/SWITCH_THEME_SUCCESS'
const SWITCH_THEME_FAILED = 'themepicker/GET_DATA_REQUEST_FAILED'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,
  SWITCH_THEME,
  SWITCH_THEME_SUCCESS,
  SWITCH_THEME_FAILED
}
