const ADD_FILTERS = 'filters/ADD_FILTERS'
const ADD_FILTERS_SUCCESS = 'filters/ADD_FILTERS_SUCCESS'
const ADD_FILTERS_FAILED = 'filters/ADD_FILTERS_FAILED'

const GET_DATA_REQUEST = 'filters/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'filters/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'filters/GET_DATA_REQUEST_FAILED'

const TOGGLE_MODAL = 'filters/TOGGLE_MODAL'
const TOGGLE_MODAL_SUCCESS = 'filters/TOGGLE_MODAL_SUCCESS'

const GET_FILTERS_REQUEST = 'filters/GET_FILTERS_REQUEST'
const GET_FILTERS_REQUEST_SUCCESS = 'filters/GET_FILTERS_REQUEST_SUCCESS'
const GET_FILTERS_REQUEST_FAILED = 'filters/GET_FILTERS_REQUEST_FAILED'

const TOGGLE_FILTER = 'filters/TOGGLE_FILTER'
const TOGGLE_FILTER_SUCCESS = 'filters/TOGGLE_FILTER_SUCCESS'
const TOGGLE_FILTER_FAILED = 'filters/TOGGLE_FILTERS_FAILED'

const CLEAN_FILTER = 'filters/CLEAN_FILTER'
const CLEAN_FILTER_SUCCESS = 'filters/CLEAN_FILTER_SUCCESS'

const DELETE_FILTERS = 'filters/DELETE_FILTERS'
const DELETE_FILTERS_SUCCESS = 'filters/DELETE_FILTERS_SUCCESS'

export {
  ADD_FILTERS,
  ADD_FILTERS_SUCCESS,
  ADD_FILTERS_FAILED,
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,
  TOGGLE_MODAL,
  TOGGLE_MODAL_SUCCESS,
  GET_FILTERS_REQUEST,
  GET_FILTERS_REQUEST_SUCCESS,
  GET_FILTERS_REQUEST_FAILED,
  TOGGLE_FILTER,
  TOGGLE_FILTER_SUCCESS,
  TOGGLE_FILTER_FAILED,
  CLEAN_FILTER,
  CLEAN_FILTER_SUCCESS,
  DELETE_FILTERS,
  DELETE_FILTERS_SUCCESS
}
