const GET_ALL_ITEMS_REQUEST = 'notifications/GET_ALL_ITEMS_REQUEST'
const GET_ALL_ITEMS_REQUEST_SUCCESS = 'notifications/GET_ALL_ITEMS_REQUEST_SUCCESS'
const GET_ALL_ITEMS_REQUEST_FAILED = 'notifications/GET_ALL_ITEMS_REQUEST_FAILED'

const TOOGLE_NOTIFICATION = 'notifications/TOOGLE_NOTIFICATION'
const TOOGLE_NOTIFICATION_SUCCESS = 'notifications/TOOGLE_NOTIFICATION_SUCCESS'

export {
    GET_ALL_ITEMS_REQUEST,
    GET_ALL_ITEMS_REQUEST_SUCCESS,
    GET_ALL_ITEMS_REQUEST_FAILED,

    TOOGLE_NOTIFICATION,
    TOOGLE_NOTIFICATION_SUCCESS
}
