const GET_DATA_REQUEST = 'notifications/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'notifications/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'notifications/GET_DATA_REQUEST_FAILED'

const TOOGLE_NOTIFICATION = 'notifications/TOOGLE_NOTIFICATION'
const TOOGLE_NOTIFICATION_SUCCESS = 'notifications/TOOGLE_NOTIFICATION_SUCCESS'

export {
    GET_DATA_REQUEST,
    GET_DATA_REQUEST_SUCCESS,
    GET_DATA_REQUEST_FAILED,

    TOOGLE_NOTIFICATION,
    TOOGLE_NOTIFICATION_SUCCESS
}
