const GET_DATA_REQUEST = 'notifications/GET_DATA_REQUEST'
const GET_DATA_REQUEST_SUCCESS = 'notifications/GET_DATA_REQUEST_SUCCESS'
const GET_DATA_REQUEST_FAILED = 'notifications/GET_DATA_REQUEST_FAILED'

const TOGGLE_NOTIFICATION = 'notifications/TOGGLE_NOTIFICATION'
const TOGGLE_NOTIFICATION_SUCCESS = 'notifications/TOGGLE_NOTIFICATION_SUCCESS'

export {
  GET_DATA_REQUEST,
  GET_DATA_REQUEST_SUCCESS,
  GET_DATA_REQUEST_FAILED,

  TOGGLE_NOTIFICATION,
  TOGGLE_NOTIFICATION_SUCCESS,
}
